services:
  notes-uws:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-uws-v1
    ports:
      - 127.0.0.1:8000:8000
    restart: always

  # pg-example:
  #   image: postgres:16.1-alpine3.19
  #   container_name: pg-example
  #   environment:
  #     - POSTGRES_USER=marcus
  #     - POSTGRES_PASSWORD=marcus
  #     - POSTGRES_DB=application
  #   volumes:
  #     - ./data/postgres/:/var/lib/postgresql/data
  #     - ./database/structure.sql:/docker-entrypoint-initdb.d/1.sql
  #     - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
  #   ports:
  #     - 127.0.0.1:5432:5432
  #   restart: always

  # redis-example:
  #   image: redis:7-alpine
  #   container_name: redis-example
  #   ports:
  #     - 127.0.0.1:6379:6379
  #   restart: always

networks:
  default:
    name: api-example-network
